### ISSUE TITLE
No module named 'roslaunch'

### ISSUE THREAD

**Issue by stephane-caron** [adamheins/xacrodoc#1]
I'm trying to convert [this Xacro file](https://github.com/RubSevian/Xiaomi_Cyberdog_3D_Model/blob/cca121992ed347013d52784defb089830abb611b/urdf/urdf/Cyberdog_new_version.xacro) as follows:

```py
from xacrodoc import XacroDoc

doc = XacroDoc.from_file("Cyberdog_new_version.xacro")
doc.to_urdf_file("Cyberdog_new_version.urdf")
```

It results in the following traceback: [traceback.txt](https://github.com/adamheins/xacrodoc/files/14356966/traceback.txt)

```
XacroException: substitution args not supported:  No module named 'roslaunch'
```

Since ROS is not required to run xacrodoc, perhaps there is another missing dependency?

### Additional context

Xacro library versions:

```console
$ pip freeze | grep xacro
xacro==1.13.3
xacrodoc==0.2.0
```

**Comment by adamheins** [comment]
Unfortunately, while ROS is not required for installation or very basic usage (e.g., resolving xacro:macros, combining multiple files), if the xacro file being compiled does make use of ROS features such as `$(find <pkg>)` or even substitution arguments, then ROS (in particular the roslaunch Python package, as you noted) is required. I've updated the README to make this clearer and also added some slightly more informative error messages.

It would be nice to be able to deal with all, or at least most, xacro files without needing the full ROS ecosystem installed, and I've been thinking about this over the past couple of days. The problem I've run into is that the ROS tooling is quite interdependent (e.g., the roslaunch package depends on rosgraph, which depends on roslib, etc.), and not designed to be installed as separate pieces, so it is quite difficult to cleanly install some self-contained subset that would support xacro.

At least for the moment, this limits xacrodoc to working with xacro files that are either quite limited in scope or simply as a convenience tool within the ROS ecosystem.

**Comment by stephane-caron** [comment]
Gotcha :ok_hand: Perhaps xacrodoc could propose something for the particular case where `$(find <same_package>)` refers to the package itself?

This is a common use of `find`. I did a quick survey on the Xacro files from [Awesome Robot Descriptions](https://github.com/robot-descriptions/awesome-robot-descriptions) for which there is no URDF, and in most cases occurrences of `find` in a file are all self-referring:

- [Cyberdog_new_version.xacro](https://github.com/RubSevian/Xiaomi_Cyberdog_3D_Model/blob/cca121992ed347013d52784defb089830abb611b/urdf/urdf/Cyberdog_new_version.xacro) :heavy_check_mark:
- [walkman.urdf.xacro](https://github.com/ADVRHumanoids/iit-walkman-ros-pkg/blob/master/walkman_urdf/urdf/walkman.urdf.xacro) :heavy_check_mark:
- [spot.urdf.xacro](https://github.com/heuristicus/spot_ros/blob/6c4ce991d50f18ebcb909a7295bae918d21d9e16/spot_description/urdf/spot.urdf.xacro) :heavy_check_mark:
- [dingo-o.urdf.xacro](https://github.com/dingo-cpr/dingo/blob/84fca4abd59181704a35a7d6d6569c2ac4453de2/dingo_description/urdf/dingo-o.urdf.xacro) :heavy_check_mark:
- [husky.urdf.xacro](https://github.com/husky/husky/blob/100563b7e4fe0867b8b8daef761656b7f8b89950/husky_description/urdf/husky.urdf.xacro) :x: (refers to another package)
- [jackal.urdf.xacro](https://github.com/jackal/jackal/blob/56e7b2ba134408fcaa7cb8d2d97b3b0307ad48d5/jackal_description/urdf/jackal.urdf.xacro) :x: (refers to another package)
- [ridgeback.urdf.xacro](https://github.com/ridgeback/ridgeback/blob/f38b7897cb3e56b1d49da9b196c28a6fc1de3e2d/ridgeback_description/urdf/ridgeback.urdf.xacro) :heavy_check_mark:
- [lite6.urdf.xacro](https://github.com/xArm-Developer/xarm_ros2/blob/7797ce30ee25551d31469485dccc0f8af4997f0b/xarm_description/urdf/lite6/lite6.urdf.xacro) :heavy_check_mark:
- [ur3e.urdf.xacro](https://github.com/ros-industrial/universal_robot/blob/06d8b9e2f5f86aa54f9f2845f11edbc84e2f951e/ur_e_description/urdf/ur3e.urdf.xacro) :heavy_check_mark:
- [vx300s.xacro](https://github.com/ian-chuang/Interbotix_ViperX_300_ROS_Control/blob/09fd69b0984772518e9879852b7e98f43477444e/vx300s_description/urdf/vx300s.xacro) :heavy_check_mark:

(This is just a quick check, I didn't do a DFS on all included files.)

I guess having a short pre-processing step to resolve `$(find <same_package>)` "manually" would allow xacrodoc to handle more files, while still falling back on the full ROS tooling when needed.

**Comment by adamheins** [comment]
I've put together a possible resolution on the [xacrofork](https://github.com/adamheins/xacrodoc/tree/xacrofork) branch - which, as the name suggests, is a sort of fork of xacro since it incorporates much of xacro's code, but I rewrote the way it finds packages to not require ROS.

In particular, xacrodoc now has a `packages` submodule which globally controls package look-up. In particular, one can do things like:

```python
import xacrodoc as xd

# xacrodoc automatically walks up the directory tree from the provided file
# path to resolve packages in $(find <pkg>) directives
doc = xd.XacroDoc.from_file("somefile.urdf.xacro")

# you can also specify a set of paths under which to look for packages (using
# the same logic used to find packages under a given catkin workspace)
paths = ["/somewhere/I/put/packages", "another/directory/with/packages"]
xd.packages.look_in(paths)

# now any packages would also be resolved by searching under the paths specified above
doc = xd.XacroDoc.from_file("somefile.urdf.xacro")
```

and this will use ROS infrastructure to find packages under the hood if available. More examples given in that branch's README.

Ultimately, this would actually make xacrodoc properly independent of ROS. I'll polish this up a little more over the next couple days, but would be happy to hear any thoughts.

**Comment by stephane-caron** [comment]
This looks awesome :star_struck:

I successfully loaded [walkman_robot.urdf.xacro](https://github.com/ADVRHumanoids/iit-walkman-ros-pkg/blob/d38fe56a844f80f699afac583faf17df5e1d5d97/walkman_urdf/urdf/walkman_robot.urdf.xacro) as follows:

```py
import xacrodoc as xd

xd.packages.look_in(["../.."])  # needed, running from same dir as xacro file

# `from_file` automatically resolves packages by looking in each parent
# directory of the given path to check for required ROS packages (as marked by
# a package.xml file)
doc = xd.XacroDoc.from_file("walkman_robot.urdf.xacro")
```

Having `from_file` look for `package.xml` while walking up makes sense, but it didn't work there because in that repository the file is named `manifest.xml` for some reason.

Alternatively (and dirtier) what [yourdfpy](https://github.com/clemense/yourdfpy) does is directory-name matching: walk up directories, and if in one parent directory we find another directory named after the package we are looking for, assume it is the package indeed. This comes with its own failure cases though, I'm mentioning it for completeness but I think what you are doing here is better :+1:

**Comment by adamheins** [comment]
Good catch, I appreciate the feedback! I didn't realize that old ROS packages using the (now long-deprecated) rosbuild system used `manifest.xml` to indicate a package (where the package name is just the directory name).

I've gone ahead and added this logic, along with some extra tests on external repositories including [iit-walkman-ros-pkg](https://github.com/ADVRHumanoids/iit-walkman-ros-pkg), which now works fine using only the default `from_file` behaviour of walking up directories.

I'm also considering adding, at some point, the option to directly give xacrodoc a `dict` mapping package names to paths. This option of course requires a little work on the user's part, but would allow maximum flexibility in indicating that a particular package should be resolved to a given path, without needing to worry about it even being a ROS package at all.

**Comment by adamheins** [comment]
Closing now that these changes have been merged into main.
